#!/bin/bash

# Index genome if needed
# bwa index 02_raw_data/genome/genome.fasta

# Map markers on genome
./01_scripts/01_bwa_w_fa.sh

# Find wanted loci from bam file
./01_scripts/02_get_wanted_loci_ids.sh 03_mapped/markers.fasta.sorted.bam

# Extract wanted loci into sam file
./01_scripts/03_get_wanted_loci_sam.py 03_mapped/markers.fasta.sam 03_mapped/wanted_loci.ids 03_mapped/wanted_loci.sam

# Get best marker pairs
./01_scripts/04_pair_markers_by_target.py 03_mapped/wanted_loci.sam 03_mapped/wanted_loci.ids 03_mapped/wanted_loci.info 10000000

# Create pairwise map comparison figures
R --slave -e 'source("01_scripts/05_create_figures.R")'
