#!/bin/bash

# Global variables
FASTA_FILE="02_data/markers.fasta"
GENOME_FILE="02_data/genome/genome.fasta"

# Indexing genome
# bwa index 02_data/genome/genome.fasta

# Test if markers.fasta file exists
no_fasta_file () {
    echo "Missing marker file: ${FASTA_FILE}"
    exit
}
test -s ${FASTA_FILE} || no_fasta_file

# Test if genome.fasta file exists
no_genome_file () {
    echo "Missing genome file: ${GENOME_FILE}"
    exit
}
test -s ${GENOME_FILE} || no_genome_file

# Test if genome is indexed
no_genome_index () {
    echo "Genome is not indexed. Index it with:"
    echo "bwa index 02_data/genome/genome.fasta"
    exit
}
test -s ${GENOME_FILE}.sa || no_genome_index

# Running MapComp
echo "Running MapComp"

# Mapping reads
./01_scripts/01_bwa_align_reads.sh

# Identify good loci
./01_scripts/02_filter_bad_loci.sh \
    03_mapped/markers.fasta.sorted.bam

# Extracting good loci
./01_scripts/03_extract_good_loci.py \
    03_mapped/markers.fasta.sam \
    03_mapped/wanted_loci.ids 03_mapped/wanted_loci.sam

# Extracting best marker pairs
./01_scripts/04_pair_markers.py \
    03_mapped/wanted_loci.sam \
    03_mapped/wanted_loci.ids \
    03_mapped/wanted_loci.info \
    10000000

# Creating figures
R --slave -e 'source("01_scripts/05_create_figures.R")'
