#!/bin/bash

# Indexing genome
# bwa index 02_data/genome/genome.fasta

# Running MapComp
echo "Running MapComp"

# Mapping reads
./01_scripts/01_bwa_w_fa.sh

# Identify good loci
./01_scripts/02_get_wanted_loci_ids.sh \
    03_mapped/markers.fasta.sorted.bam

# Extracting good loci
./01_scripts/03_get_wanted_loci_sam.py \
    03_mapped/markers.fasta.sam \
    03_mapped/wanted_loci.ids 03_mapped/wanted_loci.sam

# Extracting best marker pairs
./01_scripts/04_pair_markers_by_target.py \
    03_mapped/wanted_loci.sam \
    03_mapped/wanted_loci.ids \
    03_mapped/wanted_loci.info \
    10000000

# Creating figures
R --slave -e 'source("01_scripts/05_create_figures.R")'
